export const TableHeadings = [
  'Name',
  'Description',
  'Tags',
  'Created By',
  'Active',
  'Actions',
];

export const TableData = [
  {
    Name: 'abc 1',
    Description: 'abd desc',
    Tags: 'abctags',
    CreatedBy: 'xyz',
    Active: 'Active',
    Actions: 'Inactive',
  },
  {
    Name: 'xyz 2',
    Description: 'xyz desc',
    Tags: 'abctags',
    CreatedBy: 'xyz',
    Active: 'Inactive',
    Actions: 'Active',
  },
  {
    Name: 'abc 3',
    Description: 'abd desc',
    Tags: 'abctags',
    CreatedBy: 'xyz',
    Active: 'Active',
    Actions: 'Inactive',
  },
  {
    Name: 'xyz 4',
    Description: 'xyz desc',
    Tags: 'abctags',
    CreatedBy: 'xyz',
    Active: 'Active',
    Actions: 'Inactive',
  },
  {
    Name: 'abc 5',
    Description: 'abd desc',
    Tags: 'abctags',
    CreatedBy: 'xyz',
    Active: 'Inactive',
    Actions: 'Active',
  },
  {
    Name: 'xyz 6',
    Description: 'xyz desc',
    Tags: 'abctags',
    CreatedBy: 'xyz',
    Active: 'Active',
    Actions: 'Inactive',
  },
  {
    Name: 'abc 7',
    Description: 'abd desc',
    Tags: 'abctags',
    CreatedBy: 'xyz',
    Active: 'Inactive',
    Actions: 'Active',
  },
  {
    Name: 'xyz 8',
    Description: 'xyz desc',
    Tags: 'abctags',
    CreatedBy: 'xyz',
    Active: 'Active',
    Actions: 'Inactive',
  },
  {
    Name: 'abc 9',
    Description: 'abd desc',
    Tags: 'abctags',
    CreatedBy: 'xyz',
    Active: 'Active',
    Actions: 'Inactive',
  },
  {
    Name: 'xyz 10',
    Description: 'xyz desc',
    Tags: 'abctags',
    CreatedBy: 'xyz',
    Active: 'Inactive',
    Actions: 'Active',
  },
  {
    Name: 'abc 11',
    Description: 'abd desc',
    Tags: 'abctags',
    CreatedBy: 'xyz',
    Active: 'Active',
    Actions: 'Inactive',
  },
  {
    Name: 'xyz 12',
    Description: 'xyz desc',
    Tags: 'abctags',
    CreatedBy: 'xyz',
    Active: 'Inactive',
    Actions: 'Active',
  },
  {
    Name: 'abc 13',
    Description: 'abd desc',
    Tags: 'abctags',
    CreatedBy: 'xyz',
    Active: 'Active',
    Actions: 'Inactive',
  },
  {
    Name: 'xyz 14',
    Description: 'xyz desc',
    Tags: 'abctags',
    CreatedBy: 'xyz',
    Active: 'Active',
    Actions: 'Inactive',
  },
  {
    Name: 'abc 15',
    Description: 'abd desc',
    Tags: 'abctags',
    CreatedBy: 'xyz',
    Active: 'Inactive',
    Actions: 'Active',
  },
  {
    Name: 'xyz 16',
    Description: 'xyz desc',
    Tags: 'abctags',
    CreatedBy: 'xyz',
    Active: 'Active',
    Actions: 'Inactive',
  },
  {
    Name: 'abc 17',
    Description: 'abd desc',
    Tags: 'abctags',
    CreatedBy: 'xyz',
    Active: 'Inactive',
    Actions: 'Active',
  },
  {
    Name: 'xyz 18',
    Description: 'xyz desc',
    Tags: 'abctags',
    CreatedBy: 'xyz',
    Active: 'Active',
    Actions: 'Inactive',
  },
  {
    Name: 'abc 19',
    Description: 'abd desc',
    Tags: 'abctags',
    CreatedBy: 'xyz',
    Active: 'Active',
    Actions: 'Inactive',
  },
  {
    Name: 'xyz 20',
    Description: 'xyz desc',
    Tags: 'abctags',
    CreatedBy: 'xyz',
    Active: 'Inactive',
    Actions: 'Active',
  },
  {
    Name: 'abc 21',
    Description: 'abd desc',
    Tags: 'abctags',
    CreatedBy: 'xyz',
    Active: 'Active',
    Actions: 'Inactive',
  },
  {
    Name: 'xyz 22',
    Description: 'xyz desc',
    Tags: 'abctags',
    CreatedBy: 'xyz',
    Active: 'Inactive',
    Actions: 'Active',
  },
  {
    Name: 'abc 23',
    Description: 'abd desc',
    Tags: 'abctags',
    CreatedBy: 'xyz',
    Active: 'Active',
    Actions: 'Inactive',
  },
  {
    Name: 'xyz 24',
    Description: 'xyz desc',
    Tags: 'abctags',
    CreatedBy: 'xyz',
    Active: 'Active',
    Actions: 'Inactive',
  },
  {
    Name: 'abc 25',
    Description: 'abd desc',
    Tags: 'abctags',
    CreatedBy: 'xyz',
    Active: 'Inactive',
    Actions: 'Active',
  },
  {
    Name: 'xyz 26',
    Description: 'xyz desc',
    Tags: 'abctags',
    CreatedBy: 'xyz',
    Active: 'Active',
    Actions: 'Inactive',
  },
  {
    Name: 'abc 27',
    Description: 'abd desc',
    Tags: 'abctags',
    CreatedBy: 'xyz',
    Active: 'Inactive',
    Actions: 'Active',
  },
  {
    Name: 'xyz 28',
    Description: 'xyz desc',
    Tags: 'abctags',
    CreatedBy: 'xyz',
    Active: 'Active',
    Actions: 'Inactive',
  },
  {
    Name: 'abc 29',
    Description: 'abd desc',
    Tags: 'abctags',
    CreatedBy: 'xyz',
    Active: 'Active',
    Actions: 'Inactive',
  },
  {
    Name: 'xyz 30',
    Description: 'xyz desc',
    Tags: 'abctags',
    CreatedBy: 'xyz',
    Active: 'Inactive',
    Actions: 'Active',
  },
  {
    Name: 'abc 31',
    Description: 'abd desc',
    Tags: 'abctags',
    CreatedBy: 'xyz',
    Active: 'Active',
    Actions: 'Inactive',
  },
  {
    Name: 'xyz 32',
    Description: 'xyz desc',
    Tags: 'abctags',
    CreatedBy: 'xyz',
    Active: 'Inactive',
    Actions: 'Active',
  },
  {
    Name: 'abc 33',
    Description: 'abd desc',
    Tags: 'abctags',
    CreatedBy: 'xyz',
    Active: 'Active',
    Actions: 'Inactive',
  },
  {
    Name: 'xyz 34',
    Description: 'xyz desc',
    Tags: 'abctags',
    CreatedBy: 'xyz',
    Active: 'Active',
    Actions: 'Inactive',
  },
  {
    Name: 'abc 35',
    Description: 'abd desc',
    Tags: 'abctags',
    CreatedBy: 'xyz',
    Active: 'Inactive',
    Actions: 'Active',
  },
  {
    Name: 'xyz 36',
    Description: 'xyz desc',
    Tags: 'abctags',
    CreatedBy: 'xyz',
    Active: 'Active',
    Actions: 'Inactive',
  },
  {
    Name: 'abc 37',
    Description: 'abd desc',
    Tags: 'abctags',
    CreatedBy: 'xyz',
    Active: 'Inactive',
    Actions: 'Active',
  },
];
